site_name: Wheel Dev Note
site_author: Song Ziming
site_dir: build/site
theme: readthedocs
pages:
- '首页': index.md
- '代码风格': coding_style.md
- '内存管理':
    - '综述': memory/generic.md
    - '物理内存管理': memory/page.md
    - '虚拟内存管理': memory/slab.md
- '中断处理': interrupt.md
- 'ACPI': acpi.md
- '多核': mp.md
- 'C库': clib.h
