site_name: Wheel Dev Note
site_author: Song Ziming
theme: readthedocs
pages:
- 'Home': index.md
- 'Coding Style': coding_style.md
- 'Memory Management': memory_management.md
- 'Paging': initial_paging.md
